import { FrameworkModuleDefinition } from './contracts';

export const TAX_AI_MODULES: FrameworkModuleDefinition[] = [
  {
    id: 'dashboard',
    title: 'Work Center',
    layer: 'workspace',
    routeKey: 'dashboard',
    summary: 'Aggregates current tax position, operational tasks and risk signals.',
    owns: ['DashboardTask projections'],
    consumes: ['TaxSummary', 'Invoice[]', 'CompanySettings'],
    emits: ['tax.summary.calculated'],
    capabilities: [
      {
        id: 'dashboard.tax-position',
        title: 'Tax Position Snapshot',
        description: 'Shows income, expense, VAT, surcharge and income tax estimates.',
        layer: 'workspace',
        ownerModule: 'dashboard',
        inputs: ['TaxSummary'],
        outputs: ['DashboardTask[]'],
      },
    ],
  },
  {
    id: 'invoice-workbench',
    title: 'Invoice Workbench',
    layer: 'domain',
    routeKey: 'invoices',
    summary: 'Collects, normalizes and reviews invoices and non-invoice evidence.',
    owns: ['Invoice[]'],
    consumes: ['AI document parsing service', 'Open platform sync records'],
    emits: ['data.imported', 'invoice.reviewed', 'invoice.drafted'],
    capabilities: [
      {
        id: 'invoice.document-intake',
        title: 'Document Intake',
        description: 'Converts uploaded invoices, contracts and receipts into invoice records.',
        layer: 'domain',
        ownerModule: 'invoice-workbench',
        inputs: ['File'],
        outputs: ['Partial<Invoice>'],
      },
    ],
  },
  {
    id: 'tax-declaration',
    title: 'Tax Declaration',
    layer: 'domain',
    routeKey: 'tax',
    summary: 'Prepares VAT, income tax, payroll tax, zero declaration and R&D deduction flows.',
    owns: ['Declaration drafts', 'Employee[] tax calculations'],
    consumes: ['TaxSummary', 'Invoice[]', 'Employee[]'],
    emits: ['declaration.prepared', 'risk.reviewed'],
    capabilities: [
      {
        id: 'declaration.preparation',
        title: 'Declaration Preparation',
        description: 'Turns workspace data into declaration-ready summaries and checklists.',
        layer: 'domain',
        ownerModule: 'tax-declaration',
        inputs: ['TaxSummary', 'Invoice[]', 'Employee[]'],
        outputs: ['Declaration draft'],
      },
    ],
  },
  {
    id: 'ai-assistant',
    title: 'AI Tax Assistant',
    layer: 'assistant',
    routeKey: 'assistant',
    summary: 'Answers tax questions using workspace context, model adapters and local knowledge.',
    owns: ['ChatMessage[]', 'KnowledgeItem[]'],
    consumes: ['TaxSummary', 'Invoice[]', 'Employee[]'],
    emits: ['assistant.responded'],
    capabilities: [
      {
        id: 'assistant.contextual-tax-advice',
        title: 'Contextual Tax Advice',
        description: 'Combines user questions, tax summary and knowledge items for model responses.',
        layer: 'assistant',
        ownerModule: 'ai-assistant',
        inputs: ['Question', 'TaxSummary', 'KnowledgeItem[]'],
        outputs: ['ChatResponse'],
        integrationNotes: 'Model adapters should move behind a provider interface before production use.',
      },
    ],
  },
  {
    id: 'cross-border-tax',
    title: 'Cross-border Tax',
    layer: 'domain',
    routeKey: 'cross-border-hub',
    summary: 'Supports product classification, landed-cost estimation and overseas compliance review.',
    owns: ['Cross-border calculations'],
    consumes: ['Product info', 'TaxSummary'],
    emits: ['risk.reviewed'],
    capabilities: [
      {
        id: 'cross-border.classification',
        title: 'Product Tax Classification',
        description: 'Estimates HS code, duty, VAT and consumption tax for product imports.',
        layer: 'domain',
        ownerModule: 'cross-border-tax',
        inputs: ['Product name'],
        outputs: ['CrossBorderProductInfo'],
      },
    ],
  },
  {
    id: 'tram',
    title: 'TRAM Review',
    layer: 'governance',
    routeKey: 'tram',
    summary: 'Runs global tax review and assessment workflows for target jurisdictions.',
    owns: ['TramReport'],
    consumes: ['Product name', 'Origin country', 'Target region'],
    emits: ['risk.reviewed', 'evidence.anchored'],
    capabilities: [
      {
        id: 'tram.global-review',
        title: 'Global Tax Review',
        description: 'Produces jurisdictional tax compliance reports for cross-border activities.',
        layer: 'governance',
        ownerModule: 'tram',
        inputs: ['Product', 'Origin', 'Target region'],
        outputs: ['TramReport'],
      },
    ],
  },
  {
    id: 'evidence-ledger',
    title: 'Evidence Ledger',
    layer: 'evidence',
    routeKey: 'blockchain',
    summary: 'Tracks tamper-evident proof records for invoices, reports, declarations and amendments.',
    owns: ['Block[]'],
    consumes: ['Invoice', 'TramReport', 'Declaration draft'],
    emits: ['evidence.anchored'],
    capabilities: [
      {
        id: 'ledger.anchor-record',
        title: 'Anchor Evidence Record',
        description: 'Creates a local hash-linked evidence block for important tax artifacts.',
        layer: 'evidence',
        ownerModule: 'evidence-ledger',
        inputs: ['Evidence payload'],
        outputs: ['Block'],
      },
    ],
  },
  {
    id: 'open-platform',
    title: 'Open Platform',
    layer: 'integration',
    routeKey: 'open-platform',
    summary: 'Models connector onboarding and sync for finance, HR, payment, ecommerce and logistics apps.',
    owns: ['IntegrationApp[]', 'ApiCredential'],
    consumes: ['External connector metadata'],
    emits: ['integration.synced', 'data.imported'],
    capabilities: [
      {
        id: 'platform.connector-sync',
        title: 'Connector Sync',
        description: 'Normalizes external system data into Tax AI invoice and evidence records.',
        layer: 'integration',
        ownerModule: 'open-platform',
        inputs: ['Integration payload'],
        outputs: ['Invoice[]'],
      },
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    layer: 'governance',
    routeKey: 'settings',
    summary: 'Maintains company profile and backup/export controls.',
    owns: ['CompanySettings'],
    consumes: ['Workspace backup file'],
    emits: ['data.imported'],
    capabilities: [
      {
        id: 'settings.workspace-backup',
        title: 'Workspace Backup',
        description: 'Exports and imports local Tax AI workspace state.',
        layer: 'governance',
        ownerModule: 'settings',
        inputs: ['TaxAiWorkspaceState'],
        outputs: ['Backup JSON'],
      },
    ],
  },
];

export const getModuleByRoute = (routeKey: string) =>
  TAX_AI_MODULES.find((module) => module.routeKey === routeKey);
